export enum EventsEnum {
  TURN_ON_HIGHLIGHT_SKILL_BUTTON = 'TURN_ON_HIGHLIGHT_SKILL_BUTTON',
  TURN_OFF_HIGHLIGHT_SKILL_BUTTON = 'TURN_OFF_HIGHLIGHT_SKILL_BUTTON',
  ACTIVATE_SKILLS_SHOP_SCENE = 'ACTIVATE_SKILLS_SHOP_SCENE',
  DEACTIVATE_SKILLS_SHOP_SCENE = 'DEACTIVATE_SKILLS_SHOP_SCENE',
  ACTIVATE_PLAYER_SKILLS_SCENE = 'ACTIVATE_PLAYER_SKILLS_SCENE',
  DEACTIVATE_PLAYER_SKILLS_SCENE = 'DEACTIVATE_PLAYER_SKILLS_SCENE',
}
