export enum EventsEnum {
  TURN_ON_HIGHLIGHT_SKILL_BUTTON = 'TURN_ON_HIGHLIGHT_SKILL_BUTTON',
  TURN_OFF_HIGHLIGHT_SKILL_BUTTON = 'TURN_OFF_HIGHLIGHT_SKILL_BUTTON',
  STOP_SKILLS_SHOP_SCENE = 'STOP_SKILLS_SHOP_SCENE',
}
