export enum Event {
  TURN_ON_HIGHLIGHT_SKILL_BUTTON = 'TURN_ON_HIGHLIGHT_SKILL_BUTTON',
  TURN_OFF_HIGHLIGHT_SKILL_BUTTON = 'TURN_OFF_HIGHLIGHT_SKILL_BUTTON',
  ACTIVATE_SKILLS_SHOP_SCENE = 'ACTIVATE_SKILLS_SHOP_SCENE',
  DEACTIVATE_SKILLS_SHOP_SCENE = 'DEACTIVATE_SKILLS_SHOP_SCENE',
  ACTIVATE_PLAYER_SKILLS_SCENE = 'ACTIVATE_PLAYER_SKILLS_SCENE',
  DEACTIVATE_PLAYER_SKILLS_SCENE = 'DEACTIVATE_PLAYER_SKILLS_SCENE',
  YES_DECISION_BUTTON_SELECTED = 'YES_DECISION_BUTTON_SELECTED',
  NO_DECISION_BUTTON_SELECTED = 'NO_DECISION_BUTTON_SELECTED',
  SKILL_PURCHASED = 'SKILL_PURCHASED',
  UPDATE_PLAYER_SKILLS_SCENE = 'UPDATE_PLAYER_SKILLS_SCENE',
}
